using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: ExportFont("SansSerifExbFLF.otf", Alias = "SansSerif")]
[assembly: ExportFont("SourceSansPro-Bold.ttf", Alias = "SourceSansBlack")]
[assembly: ExportFont("Nexa Light.otf", Alias = "NexaLight")]
[assembly: ExportFont("Nexa Bold.otf", Alias = "NexaBold")]
[assembly: ExportFont("Nunito-Bold.ttf", Alias = "Nunito-Bold")]
[assembly: ExportFont("Nunito-ExtraLight.ttf", Alias = "Nunito-ExtraLight")]
[assembly: ExportFont("Nunito-Light.ttf", Alias = "Nunito-Light")]
[assembly: ExportFont("Nunito-Medium.ttf", Alias = "Nunito-Medium")]
[assembly: ExportFont("Nunito - Regular.ttf", Alias = "Nunito - Regular")]
[assembly: ExportFont("AntipastoPro-DemiBold_trial.ttf", Alias = "AntipastoPro-DemiBold")]
[assembly: ExportFont("AntipastoPro-Light_trial.ttf", Alias = "AntipastoPro-Light")]
[assembly: ExportFont("AntipastoPro-Medium_trial.ttf", Alias = "AntipastoPro-Medium")]
[assembly: ExportFont("Typo_Round_Light_Demo.otf", Alias = "Typo_Round_Light_Demo")]
[assembly: ExportFont("Typo_Round_Regular_Demo.otf", Alias = "Typo_Round_Regular_Demo")]
[assembly: ExportFont("OpenSans-Bold.ttf", Alias = "OpenSans-Bold")]
[assembly: ExportFont("OpenSans-Light.ttf", Alias = "OpenSans-Light")]
[assembly: ExportFont("OpenSans-Regular.ttf", Alias = "OpenSans-Regular")]
[assembly: ExportFont("OpenSans-Semibold.ttf", Alias = "OpenSans-Semibold")]