using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: ExportFont("SourceSansPro-Bold.ttf", Alias = "SourceSansBlack")]
[assembly: ExportFont("Typo_Round_Light_Demo.otf", Alias = "Typo_Round_Light_Demo")]
[assembly: ExportFont("Typo_Round_Regular_Demo.otf", Alias = "Typo_Round_Regular_Demo")]
[assembly: ExportFont("OpenSans-Bold.ttf", Alias = "OpenSans-Bold")]
[assembly: ExportFont("OpenSans-Light.ttf", Alias = "OpenSans-Light")]
[assembly: ExportFont("OpenSans-Regular.ttf", Alias = "OpenSans-Regular")]
[assembly: ExportFont("OpenSans-Semibold.ttf", Alias = "OpenSans-Semibold")]
[assembly: ExportFont("FredokaOne-Regular.ttf", Alias = "FredokaOne-Regular")]
[assembly: ExportFont("NotoSans-Bold.ttf", Alias = "NotoSans-Bold")]
[assembly: ExportFont("NotoSans-Regular.ttf", Alias = "NotoSans-Regular")]
[assembly: ExportFont("Roboto-Bold.ttf", Alias = "Roboto-Bold")]
[assembly: ExportFont("Roboto-Light.ttf", Alias = "Roboto-Light")]
[assembly: ExportFont("Roboto-Regular.ttf", Alias = "Roboto-Regular")]
[assembly: ExportFont("Roboto-Medium.ttf", Alias = "Roboto-Medium")]
[assembly: ExportFont("bariol_bold-webfont.ttf", Alias = "bariol_bold")]
[assembly: ExportFont("bariol_light-webfont.ttf", Alias = "Roboto-light")]
[assembly: ExportFont("bariol_regular-webfont.ttf", Alias = "Roboto-Regular")]